[core]
debug = true
heartbeat = 30
consume = "4/2,8/3,16/4"

#WEB服务器设置
[webserver]
addr = "0.0.0.0:12307"
enable_ssl = false
static_dir = "web/static"

#证书设置
[webserver.certificates]
cert = "configs/****.crt"
key = "configs/****.key"

[game-server]
host = "10.10.19.204"
port = 33251

# Mysql server config
[database]
host = "127.0.0.1"
port = 3306
dbname = "scmj"
password = "123456"
username = "root"
args = "charset=utf8mb4"
buf_size = 10
max_idle_conns = 20
max_open_conns = 15
show_sql = true

#白名单设置
[whitelist]
ip = ["10.10.*", "127.0.0.1", ".*"]

#更新设置
[update]
force = true
version = "1.9.3"
android = "https://fir.im/tand"
ios = "https://fir.im/tios"
